baseURL: https://www.example.org/
theme: hugo-apero
languageCode: en
title: Hugo Apéro
author: Alison Hill
copyright: ''
googleAnalytics: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
pagination:
  enableEmoji: yes
  ignoreFiles:
    - \.Rmd$
    - \.Rmarkdown$
    - _cache$
    - \.knit\.md$
    - \.utf8\.md$
  pagerSize: 5
  preserveTaxonomyNames: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  comments: utterances
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/favicon.ico
  giscus:
    category: Comments
    category_id: '[category ID]'
    emit_metadata: '0'
    lang: en
    mapping: pathname
    reactions_enabled: '1'
    repo: apreshill/apero
    repo_id: '[REPO ID]='
    theme: light
  headingFontFamily: sans-serif
  logo: /img/blogophonic-mark-dark.png
  mainSections:
    - blog
    - project
    - talk
  math:
    renderer: katex
  navallcaps: yes
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/papillons.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/leticiaoliveiralopes
    - icon: bluesky
      icon_pack: fab
      url: https://bsky.app/profile/leticiaespinoso.bsky.social
    - icon: instagram
      icon_pack: fab
      url: https://www.instagram.com/leticiaeoliveira
    - icon: x-twitter
      icon_pack: fab
      url: https://x.com/leticiaespinoso
    - icon: orcid
      icon_pack: ai
      url: https://orcid.org/0000-0003-2020-9269
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: sky
  twitter: apreshill
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: apreshill/apero
    theme: boxy-light
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
    - name: Contributors
      title: Contributors
      url: /contributors/
      weight: 3
  header:
    - name: About
      title: About
      url: /about/
      weight: 1
    - name: Projects
      title: Projects
      url: /project/
      weight: 2
    - name: Publications
      title: Publications
      url: /publication/
      weight: 3
    - name: CV
      title: CV
      url: /CV/
      weight: 4
    - name: Useful links
      title: Useful links
      url: /links/
      weight: 5
    - name: aRts
      title: aRts
      url: /art/
      weight: 6
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  x:
    disable: no
    enableDNT: yes
    simple: no
  youtube:
    disable: no
    privacyEnhanced: yes
